### ISSUE TITLE
Turn off node log rotation for our environments

### ISSUE THREAD

**Issue by dincho** [aeternity/infrastructure#436]
It looks like that lager log rotation conflicts with datadog log monitoring/feed, so that datadog keep the log open and lager can't rotate it, and start writing in the new log file e.g. aeternity.log.1

**Comment by dincho** [comment]
Comment by @venimus :

> we need to be able to configure the logger from the node config (aeternity.yaml). else we would have to override the configuration for all users
Lager rotation feture is disabled when 'size' is 0 and date is "" in the configuration for 'lager_file_backend'.

```
{lager, [
      {error_logger_flush_queue, false},
      {handlers, [
          {lager_console_backend, [{level, info}]},
          {lager_file_backend,
            [{file, "log/aeternity.log"}, {level, debug},
             {size, 4194303}, {date, "$D0"}, {count, 10}]}
      ]},
```


> Currently there is a key controlled some aspects of the logger under 'logging' but it only allows hwm limit and log level configuration

```
logging:
    # Controls the overload protection in the logs.
    hwm: 50
    # Sets the level of logging.
    level: debug
```
